name: dryrun

on: 
  push:
    branches-ignore:
      - 'master'
  pull_request:

env:
  air-sdk-path: ${{ github.workspace }}\air_sdk
  air-sdk-version: "32.0"

jobs:
  test-on-mac:
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache AIR SDK
      id: cache-air-sdk
      uses: actions/cache@v1
      env:
        cache-name: cache-air-sdk
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
        path: ${{ env.air-sdk-path }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
          ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Download AIR SDK
      if: steps.cache-air-sdk.outputs.cache-hit != 'true'
      run: |
        mkdir -p ${{ env.air-sdk-path }}
        wget -O AIRSDK_Compiler.dmg https://airdownload.adobe.com/air/mac/download/${{ env.air-sdk-version }}/AIRSDK_Compiler.dmg
        hdiutil attach AIRSDK_Compiler.dmg -nobrowse
        cp -rf /Volumes/AIR\ SDK/* ${{ env.air-sdk-path }}
    - name: Install ANT
      run: brew install ant
    - name: Copy keystore.p12
      id: copy_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with: 
        fileName: keystore.p12
        encodedString: ${{ secrets.keystore }}
    - name: Build Script
      working-directory: build
      run: ant -debug -verbose -noinput -Dair.sdk=${{ env.air-sdk-path }} -Dkeystore.file=${{ steps.copy_keystore.outputs.filePath }} -Dkeystore.password=${{ secrets.password }} -Dvisual.studio=${{ env.visual-studio-path }} -Dis.debug=false -Dbuild.number=${{ github.run_number }} package.on.mac
    - name: Unit Tests
      id: unit-tests
      working-directory: build
      run: ant -debug -verbose -noinput -Dair.sdk=${{ env.air-sdk-path }} -Dkeystore.file=${{ steps.copy_keystore.outputs.filePath }} -Dkeystore.password=${{ secrets.password }} -Dvisual.studio=${{ env.visual-studio-path }} -Dis.debug=false -Dbuild.number=${{ github.run_number }} test.on.mac
    - name: Upload Tests Failure Detail
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: tests_failure_on_mac.txt
        path: build/test/tests_failure.txt
    - name: Upload Unit Tests Logs
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: tests_logs_on_mac.txt
        path: build/test/tests_log.txt
   
