name: CI

on: [push]

jobs:
  build:
    
    runs-on: [windows-latest]

    env:
      air-sdk: 32.0

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Cache AIR SDK
      uses: actions/cache@v1
      env:
        cache-name: cache-air-sdk
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk }}
        path: air_sdk
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk }}
          ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install AIR SDK If Needed
      if: steps.cache-air-sdk.outputs.cache-hit != 'true'
      run: |
        If(!(Test-Path ".\air_sdk"))
        {
          New-Item -Name ".\air_sdk" -ItemType "directory" -Force | Out-Null
          Invoke-WebRequest "http://airdownload.adobe.com/air/win/download/${env:air-sdk}/AIRSDK_Compiler.zip" -OutFile ".\AIRSDK_Compiler.zip"
          Expand-Archive -Path ".\AIRSDK_Compiler.zip" -DestinationPath ".\air_sdk" | Out-Null
        }
        $env:AIR_SDK="$(pwd)\air_sdk"
    - name: Build Script
      working-directory: build
      run: ant -noinput -buildfile build.xml -Dair.sdk=${env:AIR_SDK} -Dkeystore.file=${{ secrets.keystore }} -Dkeystore.password=${{ secrets.password }} -Dis.debug=false
