name: CI

on: [push]

jobs:
  build:
    
    runs-on: [windows-latest]

    env:
      air-sdk-version: "32.0"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache AIR SDK
      uses: actions/cache@v1
      env:
        cache-name: cache-air-sdk
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
        path: air_sdk
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
          ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Copy keystore.p12
      uses: timheuer/base64-to-file@v1.0.3
      with: 
        fileName: keystore.p12
        encodedString: ${{ secrets.keystore }}
    - name: Move keystore.p12 to build directory
      run: mv keystore.p12 build
    - name: Set AIR_SDK Environment variable
      run: |
        $env:AIR_SDK="$(pwd)\air_sdk"
        echo AIRSDK=${env:AIR_SDK}
    - name: Build Script
      working-directory: build
      run: |
        echo AIRSDK=${env:AIR_SDK}
        echo ====
        ls
        echo ====
        ant -noinput -buildfile build.xml -Dair.sdk=${env:AIR_SDK} -Dkeystore.file=keystore.p12 -Dkeystore.password=${{ secrets.password }} -Dis.debug=false
    - name: Download AIR SDK
      if: steps.cache-air-sdk.outputs.cache-hit != 'true'
      run: |
        New-Item -Name ".\air_sdk" -ItemType "directory" -Force | Out-Null
        Invoke-WebRequest "http://airdownload.adobe.com/air/win/download/${env:air-sdk-version}/AIRSDK_Compiler.zip" -OutFile ".\AIRSDK_Compiler.zip"
        Expand-Archive -Path ".\AIRSDK_Compiler.zip" -DestinationPath ".\air_sdk" | Out-Null

