name: CI

on: [push]

jobs:
  build:
    
    runs-on: [windows-latest]

    env:
      air-sdk-path: ${{ github.workspace }}\air_sdk
      air-sdk-version: "32.0"
      visual-studio-path: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019"

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache AIR SDK
      uses: actions/cache@v1
      env:
        cache-name: cache-air-sdk
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
        path: ${{ env.air-sdk-path }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.air-sdk-version }}
          ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Copy keystore.p12
      id: copy_keystore
      uses: timheuer/base64-to-file@v1.0.3
      with: 
        fileName: keystore.p12
        encodedString: ${{ secrets.keystore }}
    - name: Set AIR_SDK Environment variable
      run: |
        echo AIRSDK=${{ env.air-sdk-path }}
        echo ====
        ls
        echo ====
    - name: Test Visual Studio
      run: |
        cd "C:\Program Files (x86)"
        ls
        echo ====
        cd "C:\Program Files (x86)\Microsoft Visual Studio"
        ls
        echo ====
        cd "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
        ls
        echo ====
        cd "${{ env.visual-studio-path }}"
        ls
        echo =======
    - name: Build Script
      working-directory: build
      run: |
        echo AIRSDK=${{ github.workspace }}\air_sdk
        echo AIRSDK=${{ env.air-sdk-path }}
        echo keystore.p12=${{ steps.copy_keystore.outputs.filePath }}
        echo ====
        ls
        echo ====
        ant -noinput -Dair.sdk=${{ env.air-sdk-path }} -Dkeystore.file=${{ steps.copy_keystore.outputs.filePath }} -Dkeystore.password=${{ secrets.password }} -Dvisual.studio="${{ env.visual-studio-path }}" -Dis.debug=false
    - name: Download AIR SDK
      if: steps.cache-air-sdk.outputs.cache-hit != 'true'
      run: |
        New-Item -Name ".\air_sdk" -ItemType "directory" -Force | Out-Null
        Invoke-WebRequest "http://airdownload.adobe.com/air/win/download/${env:air-sdk-version}/AIRSDK_Compiler.zip" -OutFile ".\AIRSDK_Compiler.zip"
        Expand-Archive -Path ".\AIRSDK_Compiler.zip" -DestinationPath "${{ env.air-sdk-path }}" | Out-Null

